<p>The regional capital and a major logistics hub, the Colonia system shares its name with the region as a whole and the nebula that dominates much of the skies. Over the past four years, it has grown into a system of almost half a million people, at the political and economic centre of a region of ten million. Things could easily have been very different.</p>
<p>During the 3200s, Jaques, a veteran of the Imperial-Federal conflicts common at the time, and owner of a profitable chain of station catering operations, was able to purchase an Orbis-class starport, and refit it with a hyperdrive as a (for the time) long-range exploration ship. His travels in the late 3200s were extensive and remain the topic of much speculation - all that is really known is that he returned to the edge of inhabited space in early 3301, and spent around a year refitting the station with newer FSD technology.</p>
<p>In the spring of 3302 he announced a desire to join the first Distant Worlds Expedition at Beagle Point, and with the help of the early Fuel Rats obtained the hundreds of thousands of tonnes of fuel required for this jump. Among the supplies loaded onto the station before departure were a number of unknown alien items - now recognised as Thargoid Sensors.</p>
<p>On 2 June 3302 Jaques Station, with only Jaques and a small crew remaining aboard, entered hyperspace and left the Sol region. On 3 June 3302, the Distant Worlds Expedition reported that the station had failed to arrive at Beagle Point on schedule. Searches were conducted and communications hubs opened to look for distress calls, but nothing was found until the 29 June, when Commander Cly, investigating anomalous mapping data in the Eol Prou sector, stumbled across the station's distress beacon in the RS-T d3-94 system. He docked with the station, and after verifying that immediate evacuation was unnecessary, returned to the Sol bubble at full speed to organise a full rescue.</p>
<p>The Thargoid Sensors had caused severe damage to the station's system, and forced it to exit hyperspace early. While Jaques was able to nudge the station into a safe orbit and maintain limited life support in the crew area, the stresses from both the sensors and the emergency hyperspace drop had caused severe damage to all systems.</p>
<p>A major rescue operation followed, with over ten thousand pilots bringing meta-alloys to shield against further corrosion, and a wide range of repair supplies. After around a month of effort, the station was stabilised and returned to normal operation, although the frame shift drive was irrepairably damaged and so far it has not been possible to force a replacement.</p>
<p>Unable to move on, Jaques and his rescuers made a new plan - rather than depend on endless resupply convoys from Sol, they would build and construct a new self-sufficient settlement here. "Colonia" as they called it would be independent of all superpowers, and welcoming to all fleeing the turmoil of the bubble. Jaques Station became a major logistics hub, converting supplies received from the bubble into tools for the new settlers.</p>
<p>On 8 September 3302 a mining and factory base was constructed on Colonia 2a. Colonia Hub supported a significant expansion in the system's resident population, and provided additional docking space while repairs continued on Jaques Station. As the population grew, Jaques formally set up the region's governing body - the Colonia Council.</p>
<p>Additional supplies were brought in or mined, and pilots surveyed the region for suitable places for further settlement. Towards the end of October 3302, the first systems in the region were intentionally settled, and Colonia Hub hosted a visit from the Galactic Nebula Expedition, passing through the region on their survey of the southwestern nebulae.</p>
<p>As the Colonia region has grown, infrastructure in the capital has grown to match it. A shipyard opened at Colonia Hub in April 3303 to complement the new facilities at Ratraii, and in July 3303 the Colonia Orbital outpost was constructed above it to provide additional space for the tourists now being attracted to the region, as well as extra immigration processing for the growing population.</p>
<p>As the region has expanded, so too has the Colonia Council, which consists of representatives of all of Colonia's partner organisations. Run along cooperative lines like many (though not all) of those partners, it is mainly concerned with representing the region in intergalactic politics, with operational and local matters almost entirely managed by consensus of the partner organisations. This arrangement has generally suited everyone much better than the centralised superpowers, but was seriously challenged in October 3303 by the Nameless.</p>
<p>Receiving funding from an unknown source, the Nameless launched a military coup against the Council on 19 October, attempting to take control of the Colonia Hub station and with it critical infrastructure and communications. The majority of regional pilots rallied to the Council's side, and outnumbered around 15:1 the Nameless surrendered on 26 October. It took the Nameless around 18 months to recover from this defeat, and they continued to be viewed with suspicion.</p>
<p>In January 3304, the Council obtained a civilian research cruiser following donations from the friends and colleagues of the late Commander Dove Enigma. Named after the Commander, it brought with it significant information about humanity's recent interactions with the Thargoids, and was parked in an active orbit of Colonia 3a, where it now provides additional industrial and research capacity, especially in the field of exobiology.</p>
<p>Following analysis of the Thargoid materials, the Council announced an intention to boost the region's defensive capacities - ostensibly against the Thargoids themselves, though many analysts believe that the defences are in fact intended against potential attacks by human warlords fleeing from the Thargoids, or further coup attempts. Large quantities of ore were mined, brought to the Dove Enigma and processed in early March 3304 to build the Colonia Bastion security installation in April: meanwhile, allies in the Sol bubble purchased and transferred several million tonnes of advanced military hardware to stock the installation and other classified depots around the region.</p>
<p>In June 3304, the Council commissioned a large fleet of bulk carriers, with 20 ships in total obtained to transport supplies around the region, resupply the Council's outposts on the route to Sol, and expand trade with systems in the Sol bubble. Rotating through Colonia on a 12-week cycle, these ships made the system into one of the galaxies largest logistics hubs, and cemented its role as the regional capital.</p>
<p>Jaques, returning to his pre-exploration days in catering, constructed a large cafe near Colonia 2b in December 3304, catering to locals and tourists alike, and providing higher quality accommodation for the system's increasing population. Meanwhile, research space on the Dove Enigma was becoming limited, even with the construction of extra labs in Pytheas and Tir, and so the Colonia Applied Research installation was built in June 3305 to support the development of Colonia's high-tech economy - and shipyards throughout the system now stock the first class modules it produces.</p>
<p>In common with many systems in the nebula, Colonia contains vacuum life-forms, including the famous umbrella molluscs. These have been studied extensively since their discovery, with the Holloway Biology Centre opening in December 3305 after extensive delays to investigate them in more detail.</p>
<p>In keeping with Jaques' own history as an explorer, and the profession of many of those who rescued him, the system has been involved in many major expeditions, including the Galactic Nebula Expedition in October 3302, the Mercury 7 expedition in March 3303, the Enigma and Beagle Point Expeditions in early 3304, and many more since. Hundreds of independent explorers visit Jaques Station daily, and the data collected there has been invaluable to understanding the galaxy.</p>
<p>To commemorate the original rescue of Jaques a combined exploration and supply convoy departs from the Sol bubble to the Colonia region in December of each year. The first of these, in late 3302, carried vital supplies for the growing settlement - subsequent ones have been more ceremonial in nature, bringing rare and luxury items to strengthen trade and diplomatic links between Colonia and systems in the Sol bubble.</p>
<p>In June 3306 the docks supporting the Council’s logistics fleet were extended and opened up to civilian use with the new Drake-class design. A substantial number of carriers were commissioned for independent use, including much of the Deep Space Support Array fleet, who took on fuel and supplies from the region before departing to their stations. Demand was so high that five auxiliary shipyards needed to be opened in the region's major logistics and technology hubs to service demand for fitting these ships, and the region was forced to heavily restrict civilian availability of Tritium to ensure sufficient fuel remained for the Council’s fleet.</p>
